services:
  apriltag_detection:
    container_name: my_ros2_apriltag_detection
    extends:
      #file: ../submodules/ros2-apriltags/docker/docker-compose.yml
      file: /home/sameer/sameer/iki_workspace/ros2_ws/src/mk-246904/submodules/ros-2-apriltags/docker/docker-compose.yml
      service: apriltag_detection
    command: 
    - bash 
    - -c 
    - |
        ros2 run apriltag_ros apriltag_node --ros-args -r image_rect:=/head_front_camera/rgb/image_raw -r camera_info:=/head_front_camera/rgb/camera_info  --params-file `ros2 pkg prefix apriltag_ros`/share/apriltag_ros/cfg/tags_36h11.yaml

