services:

  tiago_base:
    extends:
      file: .compose_templates.yml
      service: .tiago_sim
    
    command: 
      - bash
      - -c
      - |
        ros2 launch rwu_tiago_bringup sim_robocup_2023.launch.py is_public_sim:=True x:=-1.451 y:=-5.25 yaw:=1.57 navigation:=True slam:=False map_path:=/maps/fuinalmapFixed.yaml&
        
        sleep 1
        ros2 run gazebo_ros spawn_entity.py -entity door -database counter -x -1.50 -y -4.36 -z 0 -Y 0 &&
        ros2 action send_goal /head_controller/increment teleop_tools_msgs/action/Increment "{increment_by:[0.0,-0.8,0.1]}" &&
        
        cd /models
        python3 spawn_objects_clean_table.py &
    
        cd /iki_workspace/ros2_ws
        colcon build --packages-select clean_the_table &&
        source install/setup.bash &&
        ros2 run clean_the_table rock_and_roll
        
        tail -f /dev/null
  tiago_workspace_conainer:
    extends:
      file: .compose_templates.yml
      service: .tiago_workspace
    working_dir: /root/iki_workspace/ros2_ws
    command: 
      - bash 
      - -c 
      - |
          
        tail -f /dev/null
    
  apriltag_detection:
    container_name: my_ros2_apriltag_detection
    extends:
      #file: ../submodules/ros2-apriltags/docker/docker-compose.yml
      file: /home/sameer/sameer/iki_workspace/ros2_ws/src/mk-246904/submodules/ros-2-apriltags/docker/docker-compose.yml
      service: apriltag_detection
    command: 
    - bash 
    - -c 
    - |
        ros2 run apriltag_ros apriltag_node --ros-args -r image_rect:=/head_front_camera/rgb/image_raw -r camera_info:=/head_front_camera/rgb/camera_info  --params-file `ros2 pkg prefix apriltag_ros`/share/apriltag_ros/cfg/tags_36h11.yaml
